### ISSUE TITLE
Crashbot Phase 2

### ISSUE THREAD

**Issue by pentreathm** [decentraland/crashbot#25]
**Fixes & Improvements** 
- [x] Set a default resolution Date & Time to the current time if not previously configured when closing an incident 
- [x] Order the list of incidents in the combo by type: Open, Closed, Invalid
- [x] Create an Alert if the /list incidents endpoint is not responding 
- [x] Add automated tests to the crashbot server 
- [x] Update Banner color based on the open incident severity 

**New Features** 
- [x] Metrics Tab & Move online users metrics
- [x] Move Incidents History to its own page 
- [x] New Help page

**Status Checks**  
- [x] All Catalysts Nodes
- [x] Builder
- [x] Market Place 
- [x] Matrix

**New Metrics** 
Add new Metrics Section 
- [x] Active Users
- [x] Community Sold NFTs
- [x] Community Events 
- [x] DAO Proposals 
- [x] DAO Votes 
  

UX Design 
https://www.figma.com/file/fybEiG8qb2HaZFDnSppyLp/Status-Page?node-id=0%3A1

**Comment by pentreathm** [comment]
Metrics files 
https://cdn-data.decentraland.org/public/monthly/active-users.json
https://cdn-data.decentraland.org/public/monthly/community-events.json
https://cdn-data.decentraland.org/public/monthly/dao-proposals.json
https://cdn-data.decentraland.org/public/monthly/dao-votes.json
https://cdn-data.decentraland.org/public/monthly/community-nfts-sold.json

**Comment by pentreathm** [comment]
Builder 
https://builder-api.decentraland.org/v1/info

**Comment by pentreathm** [comment]
Marketplace 
https://nft-api.decentraland.org/health/ready
